tab_spaces = 2
max_width = 120
array_width = 120
attr_fn_like_width = 120
chain_width = 120
fn_args_layout = "Tall"
fn_call_width = 120
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Always"
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 120
struct_lit_width = 18
struct_variant_width = 35
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true


